name: Bulksplash Image Download

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  download-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Bulksplash
        run: npm install bulksplash --g

      - name: Download Images
        run: |
          bulksplash --d=images --a=200 --c=https://unsplash.com/collections/895838/people --n=1 --k=${{ secrets.UNSPLASH_API_KEY }}

      - name: Commit and push images
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add images/*
          git commit -m 'Add downloaded images'
          git push
